# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: regression
  - /task: regression
  - /optimizer: adamw
  - /scheduler: plateau
  - /callbacks: [base, checkpoint]

task:
  loss:
    _name_: mse
  metrics:
    - ${dataset.metric}

train:
  # monitor: val/${dataset.metric}
  # mode: max
  monitor: val/loss
  mode: min

encoder: id

# we need this for classification!
decoder:
  _name_: sequence
  mode: pool_masked # modified vertion of pooling embbedings for downstream tasks
