_name_: NTv2
config:
  _target_: src.models.othermodels.configuration_custom.Custom_Config
  d_model: 768 # need to change based on the model size
  model_name: NTv2
  pretrained_model_path: ${train.pretrained_model_path}