_name_: variationdataset  # this links to the overall SequenceDataset of all nucleotide transformer datasets
train_val_split_seed: ${train.seed}  # Used for train/validation splitting
dataset_name: enhancers  # this specifies which dataset in nuc trx
dest_path: null  # path to overall nuc trx datasets
max_length: ${.${.dataset_name}.max_length}
d_output: ${.${.dataset_name}.classes} 
use_padding: True
padding_side: left
add_eos: False
batch_size: 256
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
metric: ${.${.dataset_name}.metric}
# these are used to find the right attributes automatically for each dataset

breast_disease_type_classification_512:
    train_len: 14779
    max_length: 512
    classes: 4
    metric:
        - accuracy
        - f1_macro
        - mcc

cardiovascular_disorders_classification_512:
    train_len: 36480
    max_length: 512
    classes: 8
    metric:
        - accuracy
        - f1_macro
        - mcc


kidney_disease_type_classification_512:
    train_len: 11671
    max_length: 512
    classes: 7
    metric:
        - accuracy
        - f1_macro
        - mcc



pathogenicity_classification_512:
    train_len: 47121
    max_length: 512
    classes: 4
    metric:
        - accuracy
        - f1_macro
        - mcc

SpliceVarDB_1024_exonic:
    train_len: 7232
    max_length: 1024
    classes: 2
    metric:
        - accuracy
        - f1_binary
        - mcc

SpliceVarDB_1024_intronic:
    train_len: 11581
    max_length: 1024
    classes: 2
    metric:
        - accuracy
        - f1_binary
        - mcc
BRCA1_1024_coding:
    train_len: 2214
    max_length: 1024
    classes: 2
    metric:
        - accuracy
        - f1_binary
        - mcc
BRCA1_1024_noncoding:
    train_len: 900
    max_length: 1024
    classes: 2
    metric:
        - accuracy
        - f1_binary
        - mcc

BRCA2_1024_coding:
    train_len: 4939
    max_length: 1024
    classes: 2
    metric:
        - accuracy
        - f1_binary
        - mcc

BRCA2_1024_noncoding:
    train_len: 530
    max_length: 1024
    classes: 2
    metric:
        - accuracy
        - f1_binary
        - mcc




